### ISSUE TITLE
any clue on checkToken error : Expected string, got undefined ?

### ISSUE THREAD

**Issue by fghi** [jalik/meteor-jalik-ufs-local#6]
hi, i use ufs and ufs-local
works perfect on meteor 1.6.1.4
but not on meteor 1.7.0.5 : 
- the upload is stalled
- the onProgress seems not triggered

**Comment by fghi** [comment]
with more try i got the error message 

W20180925-12:26:25.725(2)? (STDERR) (node:7297) UnhandledPromiseRejectionWarning: Error: Match error: Expected string, got undefined
W20180925-12:26:25.726(2)? (STDERR)     at check (packages/check/match.js:36:17)
W20180925-12:26:25.726(2)? (STDERR)     at LocalStore.Store.self.checkToken (packages/jalik:ufs/ufs-store.js:139:17)
W20180925-12:26:25.726(2)? (STDERR)     at WebApp.connectHandlers.use (packages/jalik:ufs/ufs-server.js:149:24)
...

**Comment by fghi** [comment]
for more investigations please continue here : 

https://forums.meteor.com/t/solved-how-to-downgrade-jalik-ufs-jalik-ufs-local-issue/45685/9

**Comment by jalik** [comment]
Hello, please refer to the UFS demo to check what is different in your setup, this demo is working with the latest Meteor release available at the moment, so there should not be any problem on your side is the setup is good (packages versions of npm + meteor + local config).
https://github.com/jalik/ufs-demo

Hope that will help

**Comment by fghi** [comment]
Hi, yes i think the issue is from another package.
Does the error "checkToken -> Expected string, got undefined" give some clue ?
Thanks

**Comment by jalik** [comment]
Hi, Maybe there's something wrong on the client side, the error is telling you that a check failed, a string was needed on the server side by a method, but it was undefined, I can't tell you more, you need to read the full stack error to see where the error originated from. It could be for example a subscription problem or something like that, I don't know (hard to tell).

**Comment by fghi** [comment]
Hi, thanks for your reply. Depending how i install the app (which seems to imply different versions of dependency packages) i can avoid the issue. I'll come back when i know more ;)
